@server = https://fluffy-space-enigma-7q44xv4gp6rfw69r-8080.app.github.dev
###
GET {{server}}/api/instrumentos 
###
POST {{server}}/api/instrumentos
Content-Type: application/json

{"nombre": "Quena", "categoria": "Viento", "descripcion": "de madera resistente"}

###
GET {{server}}/api/musicos 
###
POST {{server}}/api/musicos
Content-Type: application/json

{"nombre": "Quispe J."}
